### ISSUE TITLE
Gain speed

### ISSUE THREAD

**Issue by JoSanson** [rhiever/TwitterFollowBot#68]
Hello everyone, I just tested the bot and I find them very interesting possibility. I think there is much to do but I find execution is very long! You find things to make it faster?

**Comment by rhiever** [comment]
Execution of the bot is slow because it's interacting with the Twitter API
through the internet, so it's limited by your internet speed (minor impact)
and the speed of the Twitter API. I haven't checked the Twitter API lately,
but it might be possible to perform batch operations.

Either way, you generally want to avoid making too many Twitter API calls
in a short amount of time - that angers the Twitter API gods.

On Mon, Aug 10, 2015 at 11:56 AM, Jordane <notifications@github.com> wrote:

> Hello everyone, I just tested the bot and I find them very interesting
> possibility. I think there is much to do but I find execution is very long!
> You find things to make it faster?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/68>.
>



-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by JoSanson** [comment]
Yes I understand, but I'm very well equipped with fiber optics, so it does not come to that.
You know crowdfire? It's a sass that can do the same things (in less pushed in my opinion, that's why I'm interested in TwitterFollowBot), but it's really much faster.

I'll see if there are ways to make it more efficient, for I find cool opportunity, especially for multi account.

**Comment by rhiever** [comment]
+1

Please keep us updated, thanks!

On Mon, Aug 10, 2015 at 2:06 PM, Jordane <notifications@github.com> wrote:

> Yes I understand, but I'm very well equipped with fiber optics, so it does
> not come to that.
> You know crowdfire? It's a sass that can do the same things (in less
> pushed in my opinion, that's why I'm interested in TwitterFollowBot), but
> it's really much faster.
>
> I'll see if there are ways to make it more efficient, for I find cool
> opportunity, especially for multi account.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/TwitterFollowBot/issues/68#issuecomment-129551948>
> .
>



-- 
Randal S. Olson, Ph.D.
Postdoctoral Researcher, Institute for Biomedical Informatics
University of Pennsylvania

E-mail: rso@randalolson.com | Twitter: @randal_olson
<https://twitter.com/randal_olson>
http://www.randalolson.com

**Comment by rhiever** [comment]
Closing the issue for now.
