### ISSUE TITLE
yours advises about auto_following

### ISSUE THREAD

**Issue by Fantasim** [rhiever/TwitterFollowBot#85]
I wanted to know what you think are the best times to start the bot auto_follow without being suspended by twitter.
I put auto_follow between 5 and 10 seconds that I left running 1 hour and 30 minutes a day. your opinions ?

**Comment by rl421403** [comment]
You have to make sure you did not follow too many ppl every 15 mins.

Twitter's daily limit to follow is 1000, which makes ~10 followers per 15 min on an average. But I am sure rate limit is more than that. So I am assuming it should be near 50. But you don't want to go near that number very frequently or any other rate limit.

I want to build a huge following and want to keep account for very long. That's why I do not take risk. Right now I am following 1 person every min which works great. Never had any issue. I let it run for 4 hours and a maximum of 200 follows per day.

**Comment by Fantasim** [comment]
ok thank's

**Comment by revanthrr** [comment]
can you tell me how you got it to do the delays? mine just keeps following every second :\ i am pretty new to coding, thanks :)

**Comment by Fantasim** [comment]
in your config.txt this two lines : 

FOLLOW_BACKOFF_MIN_SECONDS:5
FOLLOW_BACKOFF_MAX_SECONDS:10

**Comment by BenGosub** [comment]
Hello, I have three apps suspended in the last two weeks. For the first two times I thought I'm breaking some API limits, because I've edited the auto follow function, but then I've read this thread and I realized I probably need pauses between follows, so I've added those (1min. pause between every follow) and the app got suspended again. Now I realized that while I have pauses between follows, I don't have pauses between unfollows of non-followers, so I guess this is the reason my app got suspended, do I need pauses between unfollows too?

**Comment by revanthrr** [comment]
Ben, are you maintaining a proper ratio of atleast 1:3 :: following:followers ?

**Comment by BenGosub** [comment]
The account has approximately 1:1 following:followers ratio.

**Comment by BenGosub** [comment]
one more thing, the error I get is: {u'message': u'Invalid or expired token.', u'code': 89}  is this the error you get when your app got suspended?

**Comment by revanthrr** [comment]
1:1 is not good, try to unfollow inactive people using manageflitter then and there, also the error basically says either your app is suspended or the tokens are expired, go to apps.twitter.com and click on your app and regenerate your keys and tokens, and put the new keys to the config.txt

**Comment by BenGosub** [comment]
ok, thanks for the advice. Where can I find the managefilter, is it a part of the twitterfollowbot app?

**Comment by revanthrr** [comment]
it's a web based app manageflitter.com or try tweepi.com

**Comment by BenGosub** [comment]
ok I'll do this. Thank you again.

**Comment by rl421403** [comment]
The thing is Twitter has started cracking down heavily on users who use bots to automate follow users or like tweets.

If your actions leave foot trail for aggressive following/unfollowing then Twitter will suspend your app.

This is what working for me.

1. Auto follow users with more than 1 min delay.
    FOLLOW_BACKOFF_MIN_SECONDS:61
    FOLLOW_BACKOFF_MAX_SECONDS:70

2. I use 3-4 different apps to follow and unfollow maximum of 46 users each app per day.

3. Follow maximum of 200-230 users per day.
