### ISSUE TITLE
Authentication Error: oauth1

### ISSUE THREAD

**Issue by eljaspero** [rhiever/TwitterFollowBot#86]
Hey, first of all thank you for making this public!

Everything seems to work, except when I try to run the script. I keep getting the following Error Message:
ImportError: No module named oauth1

I tried downloading this to solve the issue:
https://github.com/requests/requests-oauthlib

However I guess I either didn't do it properly or it didn't solve the problem. Does anyone have an idea what the reason for this error message could be? (if yes, I would appreciate it if you could explain it in simple terms, I am a total novice)

**Comment by revanthrr** [comment]
i am new to this too, I assume you use windows, so here is what happened to me, i got an error that said : "Could not authenticate you" and i got this error after fixing 3-4 previous errors, in the end what i did was, i downloaded the verrsion 2.0 of this, it was uploaded on pypi.python.org here is the link to the download https://pypi.python.org/pypi/TwitterFollowBot/v2.0 it had the same thing, instructions and everything, but make sure of one thing, once you download it, when you edit the config file or any other file, use notepad++ instead of notepad or wordpad or whatever, that seems to be a problem. just try the version 2.0 and edit with notepad++ might solve the problem, it did for me.

**Comment by eljaspero** [comment]
Thanks! I wasn't able to solve it, so I tried to install the whole thing on a different computer. It worked there, so not sure what the issue was.
